description: >
  Minimal Python executor
docker:
  - image: 'python:<<parameters.tag>>'
parameters:
  tag:
    default: slim-buster
    description: >
      Pick a specific python image variant:
      https://hub.docker.com/_/python/?tab=tags
    type: string
